/* GENERATED BY CHAT GPT */

package com.archive;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api")
public class LinkController {

    private final LinkRepo repo;
    private final JdbcTemplate jdbc;

    public LinkController(LinkRepo repo, JdbcTemplate jdbc) {
        this.repo = repo;
        this.jdbc = jdbc;
    }

    @PostMapping("/links")
    public Link create(@RequestBody Map<String, String> body) {
        Link link = new Link(null, body.get("url"), "NEW", null);
        return repo.save(link);
    }

    @GetMapping("/links")
    public Iterable<Link> all() {
        return repo.findAll();
    }

    @GetMapping("/search")
    public List<Map<String,Object>> search(@RequestParam String q) {
        return jdbc.queryForList("""
            SELECT l.id, l.url, a.parsed_text
            FROM archives a
            JOIN links l ON l.id = a.link_id
            WHERE a.tsv @@ plainto_tsquery(?)
        """, q);
    }
}
