-- GENERATED BY CHAT GPT

CREATE TABLE links (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    status TEXT DEFAULT 'NEW',
    title TEXT,
    created_at TIMESTAMP DEFAULT now(),
    fetched_at TIMESTAMP
);

CREATE TABLE archives (
    id SERIAL PRIMARY KEY,
    link_id INTEGER REFERENCES links(id),
    raw_html TEXT,
    parsed_text TEXT,
    tsv tsvector
);

CREATE INDEX idx_tsv ON archives USING GIN(tsv);
