# GENERATED BY CHAT GPT

import psycopg2
import requests
from bs4 import BeautifulSoup

conn = psycopg2.connect(
    dbname="archive",
    user="archive",
    password="archive",
    host="localhost"
)

def fetch():
    cur = conn.cursor()

    cur.execute("SELECT id, url FROM links WHERE status='NEW' LIMIT 1")
    row = cur.fetchone()

    if not row:
        return

    link_id, url = row

    try:
        cur.execute("UPDATE links SET status='FETCHING' WHERE id=%s", (link_id,))
        conn.commit()

        r = requests.get(url, timeout=10)
        soup = BeautifulSoup(r.text, "html.parser")

        text = soup.get_text()

        cur.execute("""
            INSERT INTO archives (link_id, raw_html, parsed_text, tsv)
            VALUES (%s, %s, %s, to_tsvector(%s))
        """, (link_id, r.text, text, text))

        cur.execute("""
            UPDATE links
            SET status='DONE', fetched_at=now(), title=%s
            WHERE id=%s
        """, (soup.title.string if soup.title else "", link_id))

        conn.commit()

    except Exception:
        cur.execute("UPDATE links SET status='FAILED' WHERE id=%s", (link_id,))
        conn.commit()

if __name__ == "__main__":
    fetch()
